# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7870393a51fb39dacfc573ade6274db263af444813619855d6cd8a29391942ba430812def8f24499ea850da3e76eaedfa43d4590a4e92f4ea252139bbc7d7522

test:
  secret_key_base: 0b1fdf6a738cab0811121f05605ae7345aacc0f71ed11048b27da30f1473acb56705be7db97284a4a0de7c0973e367cf9f3fcba3c65f2c34cc924e2395a97041

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
